/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academico.visao;

import academico.modelo.Disciplina;
import academico.modelo.DisciplinaDAO;
import academico.modelo.pg.PostgreSQLDAOFactory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author alexromanelli
 */
public class TelaListagemDisciplina extends javax.swing.JFrame {
    
    public static TelaListagemDisciplina INSTANCIA;

    /**
     * Creates new form TelaListagemCurso
     */
    public TelaListagemDisciplina() {
        INSTANCIA = this;
        initComponents();
    }

    public void atualizarTabela() {
        ((AbstractTableModel) tDisciplinas.getModel()).fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRegistrarDisciplina = new javax.swing.JButton();
        bAlterarCurso = new javax.swing.JButton();
        bRemoverDisciplina = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDisciplinas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de disciplina - Listagem");

        bRegistrarDisciplina.setText("Registrar disciplina");
        bRegistrarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarDisciplinaActionPerformed(evt);
            }
        });

        bAlterarCurso.setText("Alterar disciplina");
        bAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarCursoActionPerformed(evt);
            }
        });

        bRemoverDisciplina.setText("Remover disciplina");
        bRemoverDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverDisciplinaActionPerformed(evt);
            }
        });

        tDisciplinas.setModel(new ModeloTabelaDisciplina());
        jScrollPane1.setViewportView(tDisciplinas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bRegistrarDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(bAlterarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(bRemoverDisciplina)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrarDisciplina)
                    .addComponent(bAlterarCurso)
                    .addComponent(bRemoverDisciplina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRegistrarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarDisciplinaActionPerformed
        TelaRegistroDisciplina trd = 
                new TelaRegistroDisciplina(
                        ((ModeloTabelaDisciplina)tDisciplinas.getModel())
                                .getColecaoDisciplina());
        trd.setVisible(true);
    }//GEN-LAST:event_bRegistrarDisciplinaActionPerformed

    private void bAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarCursoActionPerformed
        ArrayList<Disciplina> colecaoDisciplina = 
                ((ModeloTabelaDisciplina)tDisciplinas.getModel())
                    .getColecaoDisciplina();
        TelaRegistroDisciplina trd = 
                new TelaRegistroDisciplina(colecaoDisciplina, 
                        tDisciplinas.getSelectedRow());
        trd.setVisible(true);
    }//GEN-LAST:event_bAlterarCursoActionPerformed

    private void bRemoverDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverDisciplinaActionPerformed
        int indDisciplina = tDisciplinas.getSelectedRow();
        if (indDisciplina == -1) {
            JOptionPane.showMessageDialog(null,
                    "Selecione um registro antes de remover.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        ArrayList<Disciplina> colecaoDisciplina = 
                ((ModeloTabelaDisciplina)tDisciplinas.getModel())
                    .getColecaoDisciplina();
        if (JOptionPane.showConfirmDialog(null,
                "Deseja realmente excluir o registro?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            DisciplinaDAO disciplinaDAO = PostgreSQLDAOFactory.getDisciplinaDAO();
            if (disciplinaDAO.excluirDisciplina(colecaoDisciplina.get(indDisciplina))) {
                colecaoDisciplina.remove(indDisciplina);
                atualizarTabela();
            }
        }
    }//GEN-LAST:event_bRemoverDisciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagemDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagemDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagemDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagemDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagemDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterarCurso;
    private javax.swing.JButton bRegistrarDisciplina;
    private javax.swing.JButton bRemoverDisciplina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tDisciplinas;
    // End of variables declaration//GEN-END:variables
}
