/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academico.visao;

/**
 *
 * @author alexromanelli
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mCadastros = new javax.swing.JMenu();
        miAluno = new javax.swing.JMenuItem();
        miCurso = new javax.swing.JMenuItem();
        miDisciplina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Acadêmico");

        mCadastros.setText("Cadastros");

        miAluno.setMnemonic('a');
        miAluno.setText("Aluno");
        miAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlunoActionPerformed(evt);
            }
        });
        mCadastros.add(miAluno);

        miCurso.setMnemonic('c');
        miCurso.setText("Curso");
        miCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCursoActionPerformed(evt);
            }
        });
        mCadastros.add(miCurso);

        miDisciplina.setMnemonic('d');
        miDisciplina.setText("Disciplina");
        miDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDisciplinaActionPerformed(evt);
            }
        });
        mCadastros.add(miDisciplina);

        jMenuBar1.add(mCadastros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlunoActionPerformed
        TelaListagemAluno tla = new TelaListagemAluno();
        tla.setVisible(true);
    }//GEN-LAST:event_miAlunoActionPerformed

    private void miCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCursoActionPerformed
        TelaListagemCurso tlc = new TelaListagemCurso();
        tlc.setVisible(true);
    }//GEN-LAST:event_miCursoActionPerformed

    private void miDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDisciplinaActionPerformed
        TelaListagemDisciplina tld = new TelaListagemDisciplina();
        tld.setVisible(true);
    }//GEN-LAST:event_miDisciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mCadastros;
    private javax.swing.JMenuItem miAluno;
    private javax.swing.JMenuItem miCurso;
    private javax.swing.JMenuItem miDisciplina;
    // End of variables declaration//GEN-END:variables
}
